### ISSUE TITLE
critical crash when adding hundreds / thousands of spots

### ISSUE THREAD

**Issue by johndpope** [norman784/google-maps-ios-utils#1]
for (int i = 0; i < 15000; i++) {
        Spot *spot = [self generateSpot];
        [clusterManager_ addItem:spot];
    }

load the map - zoom in and zoom in - zoom in - then crash

3c2f48544d4c3e0a}}
2015-04-09 20:04:44.249 Google Maps iOS Example[18021:4013799](%28null%29) was false: Reached the max number of texture atlases, can not allocate more.

I haven't looked at your logic -but I was able to achieve better performance in my apple map based app by removing pins not on the screen. Are you drawing the clusters off the screen?

Pseudo code.
- (void)removePinsNotOnScreen {
  for (GMSMarker *marker in[markers copy]) {
      MKMapPoint pt = MKMapPointForCoordinate(marker.position);
      BOOL mapContainsAnnotation = MKMapRectContainsPoint(mapView.visibleMapRect, pt);
  
  ```
  if (!mapContainsAnnotation) {
      marker.map = nil;
      [markers removeObject:marker];
  }
  ```
  
  }
  }

**Comment by norman784** [comment]
Hi @johndpope, I've only added some improvements on this library, but I'll take a look at will try to solve it.

Regards

**Comment by johndpope** [comment]
right - I've added this issue to the master repo. I'd like to use this library - but stability is my priority.

**Comment by johndpope** [comment]
hey @norman784  - thanks for your efforts here- I'm doing some spring cleaning and closing out old tickets. 150 to go
